language: go

go:
  - tip

install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - goveralls -repotoken ajsMSLQiBuGA6ahk85DUK0sNmAK5iH5OS
